name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  # Change to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DO_SSH_KEYS }}

    - name: Deploy to DigitalOcean Droplet
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_DROPLET_IP }} << EOF
          cd /home/ellis_1/SC_WEB_APP/Sprout-Collab-BE
          git pull origin main
          . scb/bin/activate
          pip install --no-cache-dir -r requirements.txt
        EOF
